import prisma from '../config/database.js';
import config from '../config/index.js';
import { NotFoundError, ForbiddenError, BadRequestError } from '../utils/errors.js';
import { CreateCommentInput, UpdateCommentInput, ListCommentsQuery } from '../validations/commentValidation.js';
import * as notificationService from './notificationService.js';

// These types will be generated by Prisma after migration
type CommentStatus = 'VISIBLE' | 'HIDDEN' | 'DELETED';
type Prisma = any;

/**
 * Author select fields
 */
const authorSelect = {
  id: true,
  username: true,
  display_name: true,
  avatar_url: true,
  role: true,
  reputation: true,
};

/**
 * Comment select fields
 */
const commentSelect = {
  id: true,
  content: true,
  author_id: true,
  post_id: true,
  parent_id: true,
  quoted_comment_id: true,
  upvote_count: true,
  downvote_count: true,
  status: true,
  is_edited: true,
  created_at: true,
  updated_at: true,
  users: { select: authorSelect },
};

/**
 * Quoted comment select
 */
const quotedCommentSelect = {
  id: true,
  content: true,
  users: { select: authorSelect },
};

/**
 * Transform raw Prisma comment to clean API response shape.
 * Renames Prisma relation fields to frontend-expected names:
 *   users → author
 *   comments_comments_quoted_comment_idTocomments → quotedComment
 *   other_comments_comments_parent_idTocomments → replies
 *   _count.other_comments_comments_parent_idTocomments → _count.replies
 */
function transformComment(comment: any): any {
  if (!comment) return comment;

  const {
    users,
    comments_comments_quoted_comment_idTocomments,
    other_comments_comments_parent_idTocomments,
    _count,
    ...rest
  } = comment;

  const result: any = {
    ...rest,
    author: users
      ? { ...users }
      : undefined,
    quotedComment: comments_comments_quoted_comment_idTocomments
      ? {
          ...comments_comments_quoted_comment_idTocomments,
          author: comments_comments_quoted_comment_idTocomments.users,
          users: undefined,
        }
      : null,
  };

  if (other_comments_comments_parent_idTocomments) {
    result.replies = other_comments_comments_parent_idTocomments.map(transformComment);
  }

  if (_count) {
    result._count = {
      replies: _count.other_comments_comments_parent_idTocomments ?? _count.replies ?? 0,
    };
  }

  return result;
}

/**
 * Build view permission filter for category based on user role
 */
function buildViewPermissionFilter(userRole?: string): Record<string, any> | null {
  if (!userRole) {
    // Guest user: can only see posts from categories with view_permission = 'ALL'
    return { view_permission: 'ALL' };
  }
  
  const role = userRole.toUpperCase();
  
  if (role === 'ADMIN') {
    // Admin can see all posts
    return null;
  }
  
  if (role === 'MODERATOR') {
    // Moderator can see ALL, MEMBER, MODERATOR
    return { view_permission: { in: ['ALL', 'MEMBER', 'MODERATOR'] } };
  }
  
  // MEMBER can see ALL, MEMBER
  return { view_permission: { in: ['ALL', 'MEMBER'] } };
}

/**
 * Get comments for a post with flat 2-level structure
 * Level 0: Root comments (parent_id = null)
 * Level 1: All replies (parent_id != null) - flattened, no deeper nesting
 */
export async function getCommentsByPostId(
  postId: number,
  query: ListCommentsQuery,
  includeNested = true
) {
  const { page, limit, sort } = query;
  const skip = (page - 1) * limit;

  // Verify post exists
  const post = await prisma.posts.findUnique({
    where: { id: postId },
    select: { id: true, is_locked: true },
  });

  if (!post) {
    throw new NotFoundError('Post not found');
  }

  // Build order by
  let orderBy: any;
  switch (sort) {
    case 'latest':
      orderBy = { created_at: 'desc' };
      break;
    case 'popular':
      orderBy = { upvote_count: 'desc' };
      break;
    case 'oldest':
    default:
      orderBy = { created_at: 'asc' };
  }

  // Get root level comments (Level 0)
  const where: Record<string, any> = {
    post_id: postId,
    status: 'VISIBLE',
    parent_id: null, // Only get root comments
  };

  const [comments, total] = await Promise.all([
    prisma.comments.findMany({
      where,
      select: {
        ...commentSelect,
        comments_comments_quoted_comment_idTocomments: { select: quotedCommentSelect },
        // Level 1: Get ALL direct replies flattened (no nested replies)
        other_comments_comments_parent_idTocomments: includeNested
          ? {
              where: { status: 'VISIBLE' },
              select: {
                ...commentSelect,
                comments_comments_quoted_comment_idTocomments: { select: quotedCommentSelect },
                // No deeper nesting - just count for reference
                _count: { select: { other_comments_comments_parent_idTocomments: true } },
              },
              orderBy: { created_at: 'asc' },
            }
          : undefined,
        _count: { select: { other_comments_comments_parent_idTocomments: true } },
      },
      orderBy,
      skip,
      take: limit,
    }),
    prisma.comments.count({ where }),
  ]);

  // For any reply that has its own replies, we need to flatten them
  // This means if someone replies to a reply, it becomes a sibling at level 1
  const processedComments = await Promise.all(comments.map(async (comment: any) => {
    if (!comment.other_comments_comments_parent_idTocomments || comment.other_comments_comments_parent_idTocomments.length === 0) {
      return comment;
    }
    
    // Get all nested replies (replies to replies) and flatten them
    const nestedReplies: any[] = [];
    for (const reply of comment.other_comments_comments_parent_idTocomments) {
      if (reply._count?.other_comments_comments_parent_idTocomments > 0) {
        // Fetch nested replies and add them to the list
        const nested = await prisma.comments.findMany({
          where: {
            parent_id: reply.id,
            status: 'VISIBLE',
          },
          select: {
            ...commentSelect,
            comments_comments_quoted_comment_idTocomments: { select: quotedCommentSelect },
            _count: { select: { other_comments_comments_parent_idTocomments: true } },
          },
          orderBy: { created_at: 'asc' },
        });
        nestedReplies.push(...nested);
      }
    }
    
    // Merge and sort all replies by created_at
    const allReplies = [...comment.other_comments_comments_parent_idTocomments, ...nestedReplies].sort(
      (a: any, b: any) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime()
    );
    
    return {
      ...comment,
      other_comments_comments_parent_idTocomments: allReplies,
    };
  }));

  return {
    data: processedComments.map(transformComment),
    pagination: {
      page,
      limit,
      total,
      totalPages: Math.ceil(total / limit),
    },
    is_locked: post.is_locked,
  };
}

/**
 * Get comment by ID
 */
export async function getCommentById(id: number, requestingUserRole?: string) {
  const comment = await prisma.comments.findUnique({
    where: { id },
    select: {
      ...commentSelect,
      comments_comments_quoted_comment_idTocomments: { select: quotedCommentSelect },
      posts: {
        select: {
          id: true,
          categories: {
            select: {
              id: true,
              view_permission: true,
            },
          },
        },
      },
    },
  });

  if (!comment) {
    throw new NotFoundError('Comment not found');
  }

  // Check category view permission
  const viewPermissionFilter = buildViewPermissionFilter(requestingUserRole);
  if (viewPermissionFilter) {
    const hasPermission = viewPermissionFilter.view_permission === 'ALL' 
      ? comment.posts.categories.view_permission === 'ALL'
      : (viewPermissionFilter.view_permission?.in || []).includes(comment.posts.categories.view_permission);
    
    if (!hasPermission) {
      throw new ForbiddenError('You do not have permission to view this comment');
    }
  }

  // Remove the post info before returning
  const { posts: _posts, ...commentData } = comment;
  return transformComment(commentData);
}

/**
 * Get replies to a comment
 */
export async function getCommentReplies(commentId: number, page = 1, limit = 10, requestingUserRole?: string) {
  const comment = await prisma.comments.findUnique({
    where: { id: commentId },
    select: {
      id: true,
      posts: {
        select: {
          id: true,
          categories: {
            select: {
              id: true,
              view_permission: true,
            },
          },
        },
      },
    },
  });

  if (!comment) {
    throw new NotFoundError('Comment not found');
  }

  // Check category view permission
  const viewPermissionFilter = buildViewPermissionFilter(requestingUserRole);
  if (viewPermissionFilter) {
    const hasPermission = viewPermissionFilter.view_permission === 'ALL' 
      ? comment.posts.categories.view_permission === 'ALL'
      : (viewPermissionFilter.view_permission?.in || []).includes(comment.posts.categories.view_permission);
    
    if (!hasPermission) {
      throw new ForbiddenError('You do not have permission to view replies to this comment');
    }
  }

  const skip = (page - 1) * limit;

  const [replies, total] = await Promise.all([
    prisma.comments.findMany({
      where: {
        parent_id: commentId,
        status: 'VISIBLE',
      },
      select: {
        ...commentSelect,
        comments_comments_quoted_comment_idTocomments: { select: quotedCommentSelect },
      },
      orderBy: { created_at: 'asc' },
      skip,
      take: limit,
    }),
    prisma.comments.count({
      where: {
        parent_id: commentId,
        status: 'VISIBLE',
      },
    }),
  ]);

  return {
    data: replies.map(transformComment),
    pagination: {
      page,
      limit,
      total,
      totalPages: Math.ceil(total / limit),
    },
  };
}

/**
 * Check if user role meets the required permission level
 */
function checkPermission(userRole: string, requiredLevel: string): boolean {
  if (!requiredLevel || requiredLevel === 'ALL') return true;
  
  const roleHierarchy = ['MEMBER', 'MODERATOR', 'ADMIN'];
  const userLevel = roleHierarchy.indexOf(userRole.toUpperCase());
  const requiredLevelIndex = roleHierarchy.indexOf(requiredLevel);
  
  return userLevel >= requiredLevelIndex;
}

/**
 * Create a new comment
 */
export async function createComment(postId: number, data: CreateCommentInput, author_id: number, userRole: string = 'MEMBER') {
  // Verify post exists and is not locked, also get category for permission check
  const post = await prisma.posts.findUnique({
    where: { id: postId },
    select: { 
      id: true, 
      title: true, 
      author_id: true, 
      is_locked: true, 
      status: true,
      categories: {
        select: {
          id: true,
          name: true,
          comment_permission: true,
        },
      },
    },
  });

  if (!post) {
    throw new NotFoundError('Post not found');
  }

  if (post.status !== 'PUBLISHED') {
    throw new BadRequestError('Cannot comment on this post');
  }

  if (post.is_locked) {
    throw new ForbiddenError('This post is locked for comments');
  }

  // Check user's permission to comment in this category
  if (post.categories && !checkPermission(userRole, post.categories.comment_permission)) {
    throw new ForbiddenError(`You do not have permission to comment in category "${post.categories.name}". Required: ${post.categories.comment_permission}`);
  }

  // Verify parent comment if provided
  let parentComment: { id: number; author_id: number } | null = null;
  if (data.parent_id) {
    parentComment = await prisma.comments.findUnique({
      where: { id: data.parent_id },
      select: { id: true, author_id: true, post_id: true },
    }) as any;

    if (!parentComment || (parentComment as any).post_id !== postId) {
      throw new BadRequestError('Invalid parent comment');
    }
  }

  // Verify quoted comment if provided
  let quoted_comment_id: { id: number; author_id: number } | null = null;
  if (data.quoted_comment_id) {
    quoted_comment_id = await prisma.comments.findUnique({
      where: { id: data.quoted_comment_id },
      select: { id: true, author_id: true, post_id: true },
    }) as any;

    if (!quoted_comment_id || (quoted_comment_id as any).post_id !== postId) {
      throw new BadRequestError('Invalid quoted comment');
    }
  }

  // Get commenter info for notification
  const commenter = await prisma.users.findUnique({
    where: { id: author_id },
    select: { display_name: true, username: true },
  });
  const commenterName = commenter?.display_name || commenter?.username || 'Someone';

  // Create comment
  const comment = await prisma.comments.create({
    data: {
      content: data.content,
      author_id,
      post_id: postId,
      parent_id: data.parent_id,
      quoted_comment_id: data.quoted_comment_id,
    },
    select: {
      ...commentSelect,
      comments_comments_quoted_comment_idTocomments: { select: quotedCommentSelect },
    },
  });

  // Update post comment count
  await prisma.posts.update({
    where: { id: postId },
    data: { comment_count: { increment: 1 } },
  });

  // Send notifications (don't await to avoid blocking response)
  try {
    // Notify post author (if not the commenter)
    if (post.author_id !== author_id) {
      notificationService.notifyPostAuthor(
        post.author_id,
        commenterName,
        post.title,
        postId,
        comment.id
      ).catch(err => console.error('Failed to notify post author:', err));
    }

    // Notify parent comment author (if replying and not same person)
    if (parentComment && parentComment.author_id !== author_id && parentComment.author_id !== post.author_id) {
      notificationService.notifyCommentAuthor(
        parentComment.author_id,
        commenterName,
        post.title,
        postId,
        comment.id
      ).catch(err => console.error('Failed to notify parent comment author:', err));
    }

    // Notify quoted comment author (if quoting and not same person)
    if (quoted_comment_id && quoted_comment_id.author_id !== author_id && 
        quoted_comment_id.author_id !== post.author_id &&
        quoted_comment_id.author_id !== parentComment?.author_id) {
      notificationService.notifyCommentAuthor(
        quoted_comment_id.author_id,
        commenterName,
        post.title,
        postId,
        comment.id
      ).catch(err => console.error('Failed to notify quoted comment author:', err));
    }
  } catch (err) {
    console.error('Error sending comment notifications:', err);
  }

  return transformComment(comment);
}

/**
 * Update a comment
 */
export async function updateComment(id: number, data: UpdateCommentInput, userId: number, userRole: string) {
  const comment = await prisma.comments.findUnique({
    where: { id },
    include: { posts: { select: { is_locked: true } } },
  });

  if (!comment) {
    throw new NotFoundError('Comment not found');
  }

  // Only owner can edit their comment
  if (comment.author_id !== userId) {
    throw new ForbiddenError('You can only edit your own comments');
  }

  // Check if post is locked (mods can still edit)
  if (comment.posts.is_locked && userRole === 'MEMBER') {
    throw new ForbiddenError('This post is locked');
  }

  // Check edit time limit (only for regular members, not mods/admins)
  const isModOrAdmin = userRole === 'MODERATOR' || userRole === 'ADMIN';
  if (!isModOrAdmin) {
    const editTimeLimit = config.comment.editTimeLimit; // in minutes
    const commentAge = Date.now() - new Date(comment.created_at).getTime();
    const maxEditTime = editTimeLimit * 60 * 1000; // convert to milliseconds
    
    if (commentAge > maxEditTime) {
      throw new ForbiddenError(`Comments can only be edited within ${editTimeLimit} minutes of posting`);
    }
  }

  const updatedComment = await prisma.comments.update({
    where: { id },
    data: { 
      content: data.content,
      is_edited: true,
    },
    select: {
      ...commentSelect,
      comments_comments_quoted_comment_idTocomments: { select: quotedCommentSelect },
    },
  });

  return transformComment(updatedComment);
}

/**
 * Delete a comment (soft delete)
 */
export async function deleteComment(id: number, userId: number, userRole: string) {
  const comment = await prisma.comments.findUnique({
    where: { id },
    include: { posts: { select: { author_id: true } } },
  });

  if (!comment) {
    throw new NotFoundError('Comment not found');
  }

  // Check permission: comment author, post author, or mod/admin
  const isCommentAuthor = comment.author_id === userId;
  const isPostAuthor = comment.posts.author_id === userId;
  const isModOrAdmin = userRole === 'MODERATOR' || userRole === 'ADMIN';

  if (!isCommentAuthor && !isPostAuthor && !isModOrAdmin) {
    throw new ForbiddenError('You do not have permission to delete this comment');
  }

  // Soft delete
  await prisma.comments.update({
    where: { id },
    data: { status: 'DELETED' },
  });

  // Update post comment count
  await prisma.posts.update({
    where: { id: comment.post_id },
    data: { comment_count: { decrement: 1 } },
  });
}

/**
 * Hide a comment (Mod/Admin only)
 */
export async function hideComment(id: number) {
  const comment = await prisma.comments.findUnique({
    where: { id },
  });

  if (!comment) {
    throw new NotFoundError('Comment not found');
  }

  const updatedComment = await prisma.comments.update({
    where: { id },
    data: { status: comment.status === 'HIDDEN' ? 'VISIBLE' : 'HIDDEN' },
    select: commentSelect,
  });

  return transformComment(updatedComment);
}

/**
 * Get comment count for a post
 */
export async function getcomment_count(postId: number): Promise<number> {
  return prisma.comments.count({
    where: {
      post_id: postId,
      status: 'VISIBLE',
    },
  });
}









